### ISSUE TITLE
Alphabetsze list?

### ISSUE THREAD

**Issue by rmharrison** [ahmadnassri/awesome-coworking#16]
The [contributor guidelines](https://github.com/ahmadnassri/awesome-coworking/blob/master/CONTRIBUTING.md) state that additions should be alphabetical, but the underlying list is *not*, either in the individual sub-categories (e.g. Portland) or country-level categories (e.g. United States).

Would you alphabetise or accept a PR?

**Comment by ahmadnassri** [comment]
yes, PRs are welcome.
